### ISSUE TITLE
TODO: UI Issues/Requests

### ISSUE THREAD

**Issue by rmoscowitz** [sketch-city/harvey-api#31]
If you tackle one of the checkboxes below, check it off and add either a link to the PR where the issue was fixed OR add a link to the new issue for the item.

- [x] Notes field (https://github.com/sketch-city/harvey-api/pull/24)
- [x] Certain fields must be required when adding/updating (#70)
    - Shelter req'd fields: Shelter, Address, Phone
    - Need req'd fields: Location name, Location address, Contact phone number
- [x] Remove Lat/Long from the UI
- [ ] Unclear the difference between `Address Name` and `Shelter`
- [x] Add `State` field (#109)
- [x] Admins cannot delete shelters. (https://github.com/sketch-city/harvey-api/pull/24) 
- [ ] Nice to have: some shelters close but the location becomes a donation center (and should show up in the Needs list). 

*** adding more ***

- [x] Move the "Show/Update" link to column 0 (so it's visible without scrolling) (https://github.com/sketch-city/harvey-api/pull/35)
- [ ] Fix updated_by so it shows the last admin to update the record
- [x] Fix updated_at to display on the table. It currently shows last_updated which is a manual field from the google sheet. (https://github.com/sketch-city/harvey-api/pull/56)

**Comment by ironcoconut** [comment]
Notes and closing shelters here: https://github.com/sketch-city/harvey-api/pull/24/files

**Comment by ironcoconut** [comment]
Lat long in the ui is a temporary hack bc we messed up the geocoding and needed a quick way to fix it. Once the records are corrected, we can remove them.

**Comment by ironcoconut** [comment]
What are the required fields? 

I would think only adding would have required fields. 

Updating should have at least 1 field updated.

**Comment by ironcoconut** [comment]
Address name and shelter are hold overs from the Google sheet. I'm not sure the difference either. They will probably have to stay until we fix the DB schema.

**Comment by ironcoconut** [comment]
The above checkboxes can either be checked off and a link added to the PR when they are done OR they can be checked off and moved to a new issue (also add a link to the new issue).

**Comment by user512** [comment]
https://github.com/sketch-city/harvey-api/pull/109 resolves `Add State field (some shelters not in Texas)` (cannot edit the original comment)

**Comment by jwo** [comment]
I think this is pretty well updated, and we have more info (and a cooler way to find places) than when this was originally created. 

Going to close for now. Please reopen if there are more things to do
